//
// Generated file, do not edit! Created by opp_msgtool 6.3 from Blockchain.msg.
//

#ifndef __BLOCKCHAIN_M_H
#define __BLOCKCHAIN_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class TransactionMsg;
class BlockMsg;
class GossipMsg;
/**
 * Class generated from <tt>Blockchain.msg:2</tt> by opp_msgtool.
 * <pre>
 * // Blockchain.msg
 * message TransactionMsg
 * {
 *     string sender;
 *     string receiver;
 *     double amount;
 *     string signature;
 *     string txId;
 *     string data;
 *     int timestamp;
 * }
 * </pre>
 */
class TransactionMsg : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string sender;
    omnetpp::opp_string receiver;
    double amount = 0;
    omnetpp::opp_string signature;
    omnetpp::opp_string txId;
    omnetpp::opp_string data;
    int timestamp = 0;

  private:
    void copy(const TransactionMsg& other);

  protected:
    bool operator==(const TransactionMsg&) = delete;

  public:
    TransactionMsg(const char *name=nullptr, short kind=0);
    TransactionMsg(const TransactionMsg& other);
    virtual ~TransactionMsg();
    TransactionMsg& operator=(const TransactionMsg& other);
    virtual TransactionMsg *dup() const override {return new TransactionMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSender() const;
    virtual void setSender(const char * sender);

    virtual const char * getReceiver() const;
    virtual void setReceiver(const char * receiver);

    virtual double getAmount() const;
    virtual void setAmount(double amount);

    virtual const char * getSignature() const;
    virtual void setSignature(const char * signature);

    virtual const char * getTxId() const;
    virtual void setTxId(const char * txId);

    virtual const char * getData() const;
    virtual void setData(const char * data);

    virtual int getTimestamp() const;
    virtual void setTimestamp(int timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TransactionMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TransactionMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Blockchain.msg:12</tt> by opp_msgtool.
 * <pre>
 * message BlockMsg
 * {
 *     int index;
 *     string previousHash;
 *     string merkleRoot;
 *     int timestamp;
 *     string minerId;
 *     string currentHash;
 *     string transactions[];
 *     int blockHeight;
 * }
 * </pre>
 */
class BlockMsg : public ::omnetpp::cMessage
{
  protected:
    int index = 0;
    omnetpp::opp_string previousHash;
    omnetpp::opp_string merkleRoot;
    int timestamp = 0;
    omnetpp::opp_string minerId;
    omnetpp::opp_string currentHash;
    omnetpp::opp_string *transactions = nullptr;
    size_t transactions_arraysize = 0;
    int blockHeight = 0;

  private:
    void copy(const BlockMsg& other);

  protected:
    bool operator==(const BlockMsg&) = delete;

  public:
    BlockMsg(const char *name=nullptr, short kind=0);
    BlockMsg(const BlockMsg& other);
    virtual ~BlockMsg();
    BlockMsg& operator=(const BlockMsg& other);
    virtual BlockMsg *dup() const override {return new BlockMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getIndex() const;
    virtual void setIndex(int index);

    virtual const char * getPreviousHash() const;
    virtual void setPreviousHash(const char * previousHash);

    virtual const char * getMerkleRoot() const;
    virtual void setMerkleRoot(const char * merkleRoot);

    virtual int getTimestamp() const;
    virtual void setTimestamp(int timestamp);

    virtual const char * getMinerId() const;
    virtual void setMinerId(const char * minerId);

    virtual const char * getCurrentHash() const;
    virtual void setCurrentHash(const char * currentHash);

    virtual void setTransactionsArraySize(size_t size);
    virtual size_t getTransactionsArraySize() const;
    virtual const char * getTransactions(size_t k) const;
    virtual void setTransactions(size_t k, const char * transactions);
    virtual void insertTransactions(size_t k, const char * transactions);
    [[deprecated]] void insertTransactions(const char * transactions) {appendTransactions(transactions);}
    virtual void appendTransactions(const char * transactions);
    virtual void eraseTransactions(size_t k);

    virtual int getBlockHeight() const;
    virtual void setBlockHeight(int blockHeight);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BlockMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BlockMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Blockchain.msg:23</tt> by opp_msgtool.
 * <pre>
 * message GossipMsg
 * {
 *     // Types: 1=NewBlock, 2=NewTx, 3=Liveness, 4=DeadNodeReport
 *     int type;
 *     string originatorIp;
 *     int msgId;
 *     string payload;
 *     int hopCount;
 * }
 * </pre>
 */
class GossipMsg : public ::omnetpp::cMessage
{
  protected:
    int type = 0;
    omnetpp::opp_string originatorIp;
    int msgId = 0;
    omnetpp::opp_string payload;
    int hopCount = 0;

  private:
    void copy(const GossipMsg& other);

  protected:
    bool operator==(const GossipMsg&) = delete;

  public:
    GossipMsg(const char *name=nullptr, short kind=0);
    GossipMsg(const GossipMsg& other);
    virtual ~GossipMsg();
    GossipMsg& operator=(const GossipMsg& other);
    virtual GossipMsg *dup() const override {return new GossipMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getType() const;
    virtual void setType(int type);

    virtual const char * getOriginatorIp() const;
    virtual void setOriginatorIp(const char * originatorIp);

    virtual int getMsgId() const;
    virtual void setMsgId(int msgId);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GossipMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GossipMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline TransactionMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<TransactionMsg*>(ptr.get<cObject>()); }
template<> inline BlockMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<BlockMsg*>(ptr.get<cObject>()); }
template<> inline GossipMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<GossipMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __BLOCKCHAIN_M_H

