[General]
network = SupplyChainNetwork
sim-time-limit = 1000s

# Default Power
*.node[*].hashPower = 20.0 

# --- SCENARIO CONFIGURATION ---

# All seeds start immediately
*.seed[*].startUpTime = 0s

# Peers 0, 1, 2 start immediately
*.peer[0..2].startUpTime = 0s

# EVENT 1: New Node Arrival
# Peer 3 joins the network later (at t=20s)
*.peer[3].startUpTime = 20s

# EVENT 2: Node Failure
# Peer 4 starts immediately but CRASHES at t=50s
*.peer[4].startUpTime = 0s
*.peer[4].shutdownTime = 50s
